# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupCode', models.CharField(max_length=250)),
                ('courseCode', models.CharField(max_length=250)),
                ('courseName', models.CharField(max_length=250)),
                ('seatsAmount', models.CharField(max_length=50)),
                ('teacher', models.CharField(max_length=500)),
                ('courseType', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=700)),
            ],
        ),
    ]
